### ISSUE TITLE
你好，请问那个bot.zip在哪里呀，我没有在discord里找到

### ISSUE THREAD

**Issue by yahanyu** [shinkuan/Akagi#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by constellation39** [comment]
先进入 [verify ](https://discordapp.com/channels/1192792431364673577/1196484059065503776) 频道验证身份后，查看 [bot-zip](https://discordapp.com/channels/1192792431364673577/1196493825145831607) 频道

**Comment by yahanyu** [comment]
感谢，找到了
