### ISSUE TITLE
使用mitm自带的chrome加载游戏非常非常慢

### ISSUE THREAD

**Issue by tmnt2005** [shinkuan/Akagi#25]
进入游戏界面就要20-30分钟，进入对局常常卡在整理牌桌78%，要10-20分钟才能进入对局。很多贴图加载不出来，看起来像是网速很慢的样子。但是用我自己的浏览器就不会这样。请问这是怎么回事呢

**Comment by shinkuan** [comment]
由於加載各種圖片都要經過mitm，就會導致速度降低。加上你電腦規格可能不是很好。
這是正常的。

**Comment by jch12138** [comment]
为maj-soul、majsoul等域名添加分流规则，可以极大提升加载速度，我本地测试只需要十几秒就可以进入主页
