### ISSUE TITLE
autoplay在吃碰杠立/跳过选择的时候有时候定位不准

### ISSUE THREAD

**Issue by GldHkkowo** [shinkuan/Akagi#3]

**Comment by GldHkkowo** [comment]
是功能实现还是我运行环境的原因呢

**Comment by shinkuan** [comment]
尋找按鈕位置的方法我是透過OpenCV的MatchTemplate來達成的。
這個方法不是十分的穩定，一個更好的解決辦法是使用YOLO物件辨識，但我目前沒有心力去訓練一個YOLO模型來完成這件事。

**Comment by shinkuan** [comment]
最新的v1.1.0已經將Autoplay改寫： https://github.com/shinkuan/Akagi/commit/50c2982d96ecc9c4eb33fb2209029c77b8ac6586
打牌上應該變的穩定了，再試試看吧。
