### ISSUE TITLE
macOS端安装时的python版本问题

### ISSUE THREAD

**Issue by InkCoal** [shinkuan/Akagi#30]
**Describe the bug**
在macOS端进行安装时，反复遇到报错：”Python version is not in the acceptable range. Please install Python between 3.10 and 3.12.”

使用conda配置了3.10.0, 3.11.x, 3.12.x三个环境进行安装，都出现同样的报错。在安装结束后，文件夹下缺失mitm，并有如下报错：
<img width="606" alt="image" src="https://github.com/shinkuan/Akagi/assets/25706400/de1e47ad-62dc-4d32-b34c-49c86832579f">

**To Reproduce**
进行安装就会出现问题，在我的机器上稳定复现。
<img width="606" alt="image" src="https://github.com/shinkuan/Akagi/assets/25706400/db8cea9b-f1bf-4c68-b36b-7f889506edae">
<img width="606" alt="image" src="https://github.com/shinkuan/Akagi/assets/25706400/7934e6ad-1311-4552-a9dc-8888972c1694">

**Comment by shinkuan** [comment]
目前我手邊沒有Mac，沒辦法解決。

**Comment by jch12138** [comment]
你好，这个文件是我写的，最近一个月在忙毕业论文没时间维护，我今天尝试了一下，没有碰到问题
可能的原因是你电脑安装了多个版本的python，文件中检测python版本的语句是
python3 --version
你可以尝试在你的环境中运行这个代码，查看对应的版本是否符合。

一个临时的解决办法是将检测python版本的代码删除，等我这几天忙完毕业论文看一下怎么解决

<img width="737" alt="image" src="https://github.com/shinkuan/Akagi/assets/30290347/897bbe1a-52f9-454a-b009-84004b85b8ec">

**Comment by jch12138** [comment]
此外，脚本中会自行创建虚拟环境，所以你可以直接使用base环境，无需创建akagi环境

**Comment by jch12138** [comment]
我知道问题了
你在运行安装命令的时候加了sudo，然后调用了sh运行脚本，我不太清楚具体什么问题导致版本检测出了问题。
但是你只需要直接运行这个脚本，就不会出现问题。

```
chmod +x install_akagi.command
./install_akagi.command
```


<img width="971" alt="image" src="https://github.com/shinkuan/Akagi/assets/30290347/55b0118b-9957-4c73-9b10-a354f30ab9fb">
