### ISSUE TITLE
autoplay时点击的坐标错误问题，

### ISSUE THREAD

**Issue by Ruirui0719** [shinkuan/Akagi#41]
autopaly打开后每次点击的位置大概都在上家头像的位置

**Comment by shinkuan** [comment]
Won't fix until you provide details.

**Comment by Ruirui0719** [comment]
是需要补充日志文件吗

**Comment by Ruirui0719** [comment]
[akagi.log](https://github.com/shinkuan/Akagi/files/14892589/akagi.log)
在24-4-6 的13.30分左右，运行流程会显示autoplay的坐标，但是在屏幕上play的位置不对,不知道什么原因呢
![image](https://github.com/shinkuan/Akagi/assets/73934053/3ebbcfac-4d11-4cfa-ab91-ad17f014553d)

**Comment by Ruirui0719** [comment]
![image](https://github.com/shinkuan/Akagi/assets/73934053/de299ffe-96af-449a-97ff-2deebb436488)
1.6也是这样，好奇怪呀

**Comment by Ruirui0719** [comment]
就是显示何切和长条的位置

**Comment by shinkuan** [comment]
請提供以下資訊：

1. 你的螢幕解析度
2. Akagi的設定

**Comment by Ruirui0719** [comment]
![image](https://github.com/shinkuan/Akagi/assets/73934053/8aae0202-5a0c-45d0-a8df-7822e3e045df)
是这个吗，荧幕解析度没太懂？

**Comment by Ruirui0719** [comment]
![image](https://github.com/shinkuan/Akagi/assets/73934053/162a67e7-8e8b-45bf-a1ef-e47be5bcbcc0)
大概是这个吗

**Comment by shinkuan** [comment]
Try reinstalling.

**Comment by Ruirui0719** [comment]
OK

**Comment by Ruirui0719** [comment]
问题解决啦，谢谢大佬
