### ISSUE TITLE
要不要考虑把三麻需要的 libriichi 直接放在源代码里？

### ISSUE THREAD

**Issue by latorc** [shinkuan/Akagi#46]
我发现群里三麻安装对有些人比较困难，要不要考虑一下直接把三麻的libriichi包含在repo里，只需下载三麻的模型文件就能用？

例如这样：
https://github.com/latorc/MahjongCopilot/tree/main/libriichi3p

**Comment by shinkuan** [comment]
啊😧⋯⋯我是不打算公開libriichi3p的(´･_･`)

**Comment by latorc** [comment]
sorry 打扰了：） 我这去掉了，用户自己放
