### ISSUE TITLE
活动场问题

### ISSUE THREAD

**Issue by jjhjhx** [shinkuan/Akagi#47]
在某些不影响主要游戏规则的活动场（如宝牌狂热或龙之目玉），轮到自己当庄会存在读牌与autoplay失效，我不知道1.6版本是否修复了，如已修复请关闭
**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [1.5.0]

**Comment by shinkuan** [comment]
目前沒有打算支持活動場
