### ISSUE TITLE
自动进行多局比赛

### ISSUE THREAD

**Issue by duj12** [shinkuan/Akagi#53]
现在应该只能够进行单局比赛，结束后，还需要人工选择新的对局以继续。
能够直接使用鼠标控制选择对局嘛？
比如，在setting中，加入游戏场（如玉之间，四人南）的选项，同时给一个自动继续对局的选项。

**Comment by HALF111** [comment]
@duj12 您好，想咨询一下自动继续对局的这个问题您解决了么

**Comment by duj12** [comment]
> @duj12 您好，想咨询一下自动继续对局的这个问题您解决了么

我用另一个项目 https://github.com/latorc/MahjongCopilot 这个可以实现自动对局。

**Comment by HALF111** [comment]
> > @duj12 您好，想咨询一下自动继续对局的这个问题您解决了么
> 
> 我用另一个项目 https://github.com/latorc/MahjongCopilot 这个可以实现自动对局。

好的我去看一看，多谢您的解答了～
