### ISSUE TITLE
Setup Issue: MJAI Not Responding To POST Requests

### ISSUE THREAD

**Issue by Xaoilin** [shinkuan/Akagi#8]
**Describe the bug**
I get this bug when starting a friendly game in web browser
<img width="735" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/afe0d597-3476-4b60-bd9b-57e02207ffdf">

I get a Remote Disconnection error on the terminal when entering a game.

I started up my own docker  instances from `akagi.log` and I can do GET request with 200 OK. But the code always fails when attempting this POST request:

`[{"type": "start_game", "id": 2}]`

I cannot do POST requests to my docker instances with the above payload (and neither can the code in `player.py` `react` function. 

I think the MJAI Server is not setup properly or something? 

**To Reproduce**
1. Run `python mitm_playwright.py`
2. Run Proxifier
3. Run `python client.py`
4. Start a friendly game with AI bots

**Expected behavior**
The `client.py` terminal to show the normal screen reading information for the game.

**Screenshots**
Full Error:

<img width="1119" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/595833dd-da8e-4ecd-aec9-8f408fc23171">

Docker instances:

<img width="951" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/509534d8-2f20-4bc4-b2fd-f5be5413f5b7">

MITM Running correctly:

<img width="422" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/d4b719e1-d472-448a-a173-26e7a5d31096">

Proxifier setup:

<img width="329" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/ac5166a0-3eba-407d-88cc-c646dd00047f">

<img width="531" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/83bcfbaa-5cfb-4e4e-beae-4315cea0df5a">

Web browser playing the game from playwright:

<img width="1502" alt="image" src="https://github.com/shinkuan/Akagi/assets/13015141/93ab011b-aa0a-4cc5-966d-a2743c6f32a9">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I debugged the problem to the following:

**Comment by shinkuan** [comment]
Solved on discord. The user didn't have the correct bot.zip placed in the ./players folder.
